dist: focal
language: minimal
services:
  - docker

jobs:
  include:
    - name: Test Alpine
      script:
        - |
          printf 'set -eu
          apk update && apk add meson wayland-dev musl-dev wayland-protocols gcc
          meson build && ninja -C build && meson test -C build
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
    - name: Test Archlinux
      script:
        - |
          printf 'set -eu
          pacman -Sy --noconfirm gcc pkgconf meson wayland wayland-protocols
          meson build && ninja -C build && meson test -C build
          ' | docker run -i -v "$PWD":/wob -w /wob archlinux:latest
    - name: Test FreeBSD
      os: freebsd
      language: c
      compiler: clang
      script:
        - sudo pkg install -y meson pkgconf wayland wayland-protocols
        # Fix for https://reviews.freebsd.org/D25554
        - sed -i '' 's/_POSIX_C_SOURCE 199506L/_POSIX_C_SOURCE 200112L/' log.c
        - meson build && ninja -C build && meson test -C build
    - name: Coding style check
      script:
        - |
          printf 'set -eu
          apk update && apk add clang
          clang-format *.c tests/*.c --output-replacements-xml | (! grep "</replacement>" 1>/dev/null)
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
    - name: Clang static analyzer
      script:
        - |
          printf 'set -eu
          apk update && apk add meson wayland-dev musl-dev wayland-protocols gcc clang-analyzer
          scan-build meson build && scan-build --status-bugs ninja -C build
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
    - name: Valgrind
      script:
        - |
          printf 'set -eu
          apk update && apk add meson wayland-dev musl-dev wayland-protocols gcc valgrind
          meson build && meson test -C build --wrap="valgrind --leak-check=full --error-exitcode=2"
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
